### ISSUE TITLE
Font Size, Too Small in mobile.

### ISSUE THREAD

**Issue by imarchit19** [imarchit19/Game-Mania#2]
Change it via media queries.

**Comment by Divyanshwick** [comment]
Hey, I want to contribute to this issue.

**Comment by amanraj862** [comment]
hey can i contribute in any way?

**Comment by pranjalguptaneo** [comment]
Do assign it to me.

**Comment by RajSolai** [comment]
I made the changes , Nice work Pal ! #5

**Comment by imarchit19** [comment]
@RajSolai I had already assigned it to someone, will see what to do.

**Comment by RajSolai** [comment]
@imarchit19  Fine Pal, Nice work tho , I might connect with you in Linkedin
